config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :dashboard, :events,:artpromo
  root to: "homepage#index"
  #match ':controller(/:action(/:id))',:via => get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artpromo.rb
class Artpromo < ApplicationRecord

  has_many :userartpromos
  has_many :users, through: :userartpromos


end

app/controllers/artpromo_controller.rb
class ArtpromoController < ApplicationController

	before_filter :authenticate_user!

	def new

		@artpromo = current_user.artpromos.build
		#@artpromo = Artpromo.new 
		
		logger.info @artpromo

	end

	def create


		@Artistspromoter= current_user.artpromos.create(artpromo_params)

	
		redirect_to dashboard_index_url

	end

	def show
		@artpromo = Artpromo.find(params[:id])

    end

    def edit
    	@artpromo = Artpromo.find(params[:id])

    end	

    def update
 		@artpromo = Artpromo.find(params[:id])

 		if @artpromo.update_attributes(artpromo_params)
 			redirect_to dashboard_index_url, :notice => "Updated"
 		else
 			render "edit", :notice => "Error"
 		end
  
    end	



	private
		def artpromo_params
			params.require(:artpromo).permit(:name,:country,:city,:facebook,:soundcloud,:website,:genre,:artist_or_promoter) 
		end

end

app/views/artpromo/_artpromoform.html.erb
<%= form_for :artpromo, url: artpromo_index_path(current_user.id) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

   <p>
    <%= f.label :facebook, "Facebook Page" %><br>
    <%= f.text_field :facebook %>
  </p>


   <p>
    <%= f.label :soundcloud, "Soundcloud Page" %><br>
    <%= f.text_field :soundcloud %>
  </p>

   <p>
    <%= f.label :website, "Website" %><br>
    <%= f.text_field :website %>
  </p>

  <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </p>

 
  <p>
    <%= f.label :artist_or_promoter, "Are you and Artist or a promoter?" %><br>
    <%= f.select :artist_or_promoter, ['Artist', 'Promter']%>
  </p>

 
  <p>
    <%= f.submit "Save" %>
  </p>

  <% end %>

app/views/artpromo/edit.html.erb
<H1>Edit Post </H1>
<%= render partial:"artpromoform" %>

app/views/artpromo/new.html.erb
<h1>Create a new artist</h2>

<%= render partial:"artpromoform" %>